### ISSUE TITLE
有时排名上升也会提示排名变动并重复提示

### ISSUE THREAD

**Issue by zk775622756** [lulu666lulu/pcrjjc#13]
例如   我从13打到3
有时候会报3->13
并在几分钟后重复一次

**Comment by lulu666lulu** [comment]
你怕不是刷新时间调小于5分钟了吧

**Comment by fengjk12138** [comment]
当前github代码是用的1min，是不是push错版本了
在`__init__.py`的`217`行
`@sv.scheduled_job('interval', minutes=1)` @lulu666lulu
