### ISSUE TITLE
对{id}的检查出错

### ISSUE THREAD

**Issue by ZENCZOPE** [lulu666lulu/pcrjjc#14]
启动了debug模式，没有输出错误信息，日志如下（id已隐藏）：

[2021-02-02 14:25:53,933 竞技场推送] INFO: Scheduled job on_arena_schedule start.
[2021-02-02 14:25:55,629 竞技场推送] INFO: 对{id}的检查出错
[2021-02-02 14:25:55,629 竞技场推送] INFO: Scheduled job on_arena_schedule completed.
[2021-02-02 14:26:53,980 竞技场推送] INFO: Scheduled job on_arena_schedule start.
[2021-02-02 14:26:55,596 竞技场推送] INFO: 对{id}的检查出错
[2021-02-02 14:26:55,596 竞技场推送] INFO: Scheduled job on_arena_schedule completed.

**Comment by lulu666lulu** [comment]
请手动调用cdn尝试

**Comment by lulu666lulu** [comment]
另若刷新间隔小于5min会被接口拉黑

**Comment by ZENCZOPE** [comment]
> 另若刷新间隔小于5min会被接口拉黑

这个接口是你提供的吗？我看代码里默认是一分钟执行一次。

**Comment by lulu666lulu** [comment]
别去群里下）

**Comment by ZENCZOPE** [comment]
> 请手动调用cdn尝试

我在主机上使用java调用url，是没问题的。

**Comment by ZENCZOPE** [comment]
> 别去群里下）

我是这里下的啊-.-  
@sv.scheduled_job('interval', minutes=1) 这个是指的间隔一分钟吧

**Comment by lulu666lulu** [comment]
用的哪个url

**Comment by lulu666lulu** [comment]
那没事了（反正没太快一般没事
cf的尿性懂得都懂

**Comment by ZENCZOPE** [comment]
> 用的哪个url

help.tencentbot.top/enqueue?full=true&target_viewer_id=
help.tencentbot.top/query?request_id=

**Comment by lulu666lulu** [comment]
那你把接口返回print看看

**Comment by ZENCZOPE** [comment]
> 那你把接口返回print看看
1
{
  "reqeust_id": "d74a5ec2-cb28-42cd-b4b0-a157cb9e7065"
}


2
{
  "status": "queue",
  "pos": 800
}
{
  "status": "done",
  "data": {
    "user_info": {
      "arena_rank": 9,
      "grand_arena_rank": 39
    }
  }
}

**Comment by lulu666lulu** [comment]
正常的

**Comment by ZENCZOPE** [comment]
> 正常的

是系统环境的问题吗？
之前报错是这样的：

> /home/qqbot/qqbot/hoshinoBot/HoshinoBot/hoshino/modules/arena_query_push/queryapi.py:9: RuntimeWarning: coroutine 'get' was never awaited
Coroutine created at (most recent call last)
File "/home/.local/lib/python3.8/site-packages/aiocqhttp/init.py", line 210, in run
self._server_app.run(host=host, port=port, *args, **kwargs)
File "/home/.local/lib/python3.8/site-packages/quart/app.py", line 1621, in run
loop.run_until_complete(task)
File "/usr/local/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
self.run_forever()
File "/usr/local/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
self._run_once()
File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1851, in _run_once
handle._run()
File "/usr/local/lib/python3.8/asyncio/events.py", line 81, in _run
self._context.run(self._callback, *self._args)
File "/home/.local/lib/python3.8/site-packages/apscheduler/executors/base_py3.py", line 29, in run_coroutine_job
retval = await job.func(*job.args, **job.kwargs)
File "/home/qqbot/qqbot/hoshinoBot/HoshinoBot/hoshino/service.py", line 325, in wrapper
ret = await func()
File "/home/qqbot/qqbot/hoshinoBot/HoshinoBot/hoshino/modules/arena_query_push/init.py", line 215, in on_arena_schedule
res = await getprofile(int(binds["arena_bind"][user]["id"]))
File "/home/qqbot/qqbot/hoshinoBot/HoshinoBot/hoshino/modules/arena_query_push/queryapi.py", line 9, in getprofile
reqid = json.loads(await aiorequests.get(f'{apiroot}/enqueue?full={full}&target_viewer_id={viewer_id}').content.decode('utf8'))['reqeust_id']
reqid = json.loads(await aiorequests.get(f'{apiroot}/enqueue?full={full}&target_viewer_id={viewer_id}').content.decode('utf8'))['reqeust_id']
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

**Comment by lulu666lulu** [comment]
你装的是啥版本的request

**Comment by ZENCZOPE** [comment]
> 你装的是啥版本的request

requests          2.24.0
requests-cache    0.5.2
requests-oauthlib 1.3.0

**Comment by lulu666lulu** [comment]
那aiorequest呢

**Comment by ZENCZOPE** [comment]
aio-requests      1.0.0
aiocache          0.11.1
aiocqhttp         1.3.0
aiofiles          0.5.0
aiohttp           3.6.2


> 那aiorequest呢

**Comment by lulu666lulu** [comment]
更新看看（

**Comment by lulu666lulu** [comment]
要不你改成request

**Comment by ZENCZOPE** [comment]
> 更新看看（

Package           Version   Latest    Type
----------------- --------- --------- -----
aiofiles          0.5.0     0.6.0     wheel
aiohttp           3.6.2     3.7.3     wheel
APScheduler       3.6.3     3.7.0     wheel
attrs             19.3.0    20.3.0    wheel
beautifulsoup4    4.9.1     4.9.3     wheel
certifi           2020.6.20 2020.12.5 wheel
chardet           3.0.4     4.0.0     wheel
h11               0.10.0    0.12.0    wheel
h2                3.2.0     4.0.0     wheel
hpack             3.0.0     4.0.0     wheel
httpcore          0.10.1    0.12.3    wheel
httpx             0.14.1    0.16.1    wheel
Hypercorn         0.10.2    0.11.2    wheel
hyperframe        5.2.0     6.0.0     wheel
idna              2.10      3.1       wheel
Jinja2            2.11.2    2.11.3    wheel
kiwisolver        1.2.0     1.3.1     wheel
lxml              4.5.2     4.6.2     wheel
matplotlib        3.3.1     3.3.4     wheel
multidict         4.7.6     5.1.0     wheel
nonebot           1.6.0     1.8.2     sdist
numpy             1.19.1    1.20.0    wheel
Pillow            7.2.0     8.1.0     wheel
pip               20.1.1    21.0.1    wheel
pygtrie           2.3.3     2.4.2     sdist
pytz              2020.1    2021.1    wheel
Quart             0.11.5    0.14.1    wheel
requests          2.24.0    2.25.1    wheel
setuptools        47.1.0    53.0.0    wheel
sniffio           1.1.0     1.2.0     wheel
sogou-tr-free     0.0.10    0.0.11    sdist
soupsieve         2.0.1     2.1       wheel
tinydb            4.1.1     4.3.0     wheel
toml              0.10.1    0.10.2    wheel
TwitterAPI        2.5.13    2.6.5     sdist
typing-extensions 3.7.4.2   3.7.4.3   wheel
urllib3           1.25.10   1.26.3    wheel
wsproto           0.15.0    1.0.0     wheel
yarl              1.5.1     1.6.3     wheel
 更新哪一个

**Comment by lulu666lulu** [comment]
你没用hoshino吗

**Comment by ZENCZOPE** [comment]
> 你没用hoshino吗

用了，引入组件版本：
nonebot[scheduler]~=1.6.0
aiocqhttp>=1.2
lxml>=4.4.1
pytz>=2019.3
requests>=2.22.0
sogou_tr_free>=0.0.6
zhconv>=1.4.0
Pillow>=6.2.1
TwitterAPI>=2.5.10
matplotlib>=3.2.0
numpy>=1.18.0
beautifulsoup4>=4.9.0
pygtrie>=2.0
tinydb>=4.0
aiohttp>=3.6
aio_requests>=1.0.0

**Comment by lulu666lulu** [comment]
感觉你有问题（要不你改成requesr吧

**Comment by ZENCZOPE** [comment]
> 感觉你有问题（要不你改成requesr吧

请问具体怎么修改？专职java 对python不是很了解
from hoshino.aiorequests import get改成
from hoshino.requests import get报错了
