### ISSUE TITLE
[question] api是免费的,还是收费的

### ISSUE THREAD

**Issue by huang12zheng** [lulu666lulu/pcrjjc#8]
1. arena_query_push里的接口是免费的,还是收费的?
2. 收费的话,是什么样子的,哪里咨询?
api: https://help.tencentbot.top

**Comment by lulu666lulu** [comment]
目前免费

**Comment by huang12zheng** [comment]
接口有考虑商用吗? (主要想让你提高一下响应能力)

~~刚刚试了试, 应该是挂了的.卡着不动了~~
又可以了

```
https://help.tencentbot.top/query?request_id=1a80643f-a72f-4a42-b560-b8d949ab52c8
{
  "status": "queue",
  "pos": 223
}
```

**Comment by huang12zheng** [comment]
https://help.tencentbot.top/query?request_id=e9e0f3a0-1cda-42b1-9d9a-0246fe8c40d0
